### ISSUE TITLE
Bad redirect back from poll detail page to profile page

### ISSUE THREAD

**Issue by fengruigan** [fcchung/pollmaster#19]
The back button does not work as intended going from profile page to poll detail page.

**Comment by fcchung** [comment]
can you do useHistory and go back -1?

**Comment by fengruigan** [comment]
Fixed using window.history.state.
Using only useNavigate(-1) may result in the redirect exiting our domain. For example, as we can share the poll link, when a user goes to the poll from about:blank using the poll link and hit back, useNavigate(-1) will redirect the user to the about:blank.
react-router-dom has a state attached to history, and we could conditionally check if the state exists. If it does, we go back, if not, we go to home. And more customized redirects could be done in a similar fashion.
